### PR TITLE
Vault Search

### PR DESCRIPTION
**Pull request by 7Mik**
Search the entire vault Titles / Contents.
Related to issue #120 and #93

Using [Minisearch.js](https://github.com/lucaong/minisearch)

Only the index creation is ready. Will create a .json from all the html files stored in the export directory (potential flaw/feature) and store it in the export directory.

I will focus on fixing the backend for now.
Frontend support should be as easy as adding <input type="search"> filed where you want it and style it how you want it and I would rather leave it to you since you seemed to have an idea on how to style it. I will be working on the search.js for the frontend too.

This pull is extremely dirty. The search.ts has dirty module importing and I forgot to add the dependencies in the requirements, I would appreciate if you could look into it

### CODE REVIEW

**Comment by KosmosisDire** [comment]
Awesome, if in the code you could "brand" this as a general indexing rather than creating an index only for search, I think this data could be used for other purposes as well in the future, and creating to be extensible is favorable.

Also keep in mind that obsidian already has a very versatile index of all the files and metadata that you can likely use instead of a 3rd party library.

Thank you for taking the time to tackle this issue!

**Comment by 7Mik** [comment]
> Awesome, if in the code you could "brand" this as a general indexing rather than creating an index only for search, I think this data could be used for other purposes as well in the future, and creating to be extensible is favorable.
> 
> Also keep in mind that obsidian already has a very versatile index of all the files and metadata that you can likely use instead of a 3rd party library.
> 
> Thank you for taking the time to tackle this

> Awesome, if in the code you could "brand" this as a general indexing rather than creating an index only for search, I think this data could be used for other purposes as well in the future, and creating to be extensible is favorable.
> 
> Also keep in mind that obsidian already has a very versatile index of all the files and metadata that you can likely use instead of a 3rd party library.
> 
> Thank you for taking the time to tackle this issue!

Sure, I will edit the branding.

AFAIK the new index generation is required because of people choosing only certain documents to export and not the whole vault, but if you know a faster and reliable way of indexing and generating a json with Title and content feel free to step in and I will focus only on the frontend searching implementation!

**Comment by 7Mik** [comment]
This should be the last commit for the index generator.

Also committed the updated package and package lock.

The index now has relative path, and doesn't encounter word merging bugs with li and ul tags in lists (need experimentation because there might be more tags that cause this issue).

The index generation is now extremely faster and generates a json that is 4 times smaller than in the first version.

Next step is implementing a search frontend script.

**Comment by KosmosisDire** [comment]
Obsidian's index can be filtered im pretty sure to only include certain files. But id have to look to see if it can do what we would want.

**Comment by 7Mik** [comment]
> Obsidian's index can be filtered im pretty sure to only include certain files. But id have to look to see if it can do what we would want.

I think that after using the obsidian index we would still need to go and parse it to make it supported by the search frontend script so going this way might be faster

**Comment by KosmosisDire** [comment]
What format will this json file be, is the goal just to have a dictionary that associates the file name with the text of the document?

**Comment by 7Mik** [comment]
> What format will this json file be, is the goal just to have a dictionary that associates the file name with the text of the document?
[searchIndex.json](https://github.com/KosmosisDire/obsidian-webpage-export/files/13845112/searchIndex.json)

This is my searchindex generated from approximately 350 documents

**Comment by KosmosisDire** [comment]
It should be possible to create the index during generation rather than trying to create an index retroactively. Because during generation we have a list of all the files being exported as well as their paths, content, names, etc

**Comment by KosmosisDire** [comment]
Ahhhh okay the file you sent me makes a lot more sense

**Comment by 7Mik** [comment]
> It should be possible to create the index during generation rather than trying to create an index retroactively. Because during generation we have a list of all the files being exported as well as their paths, content, names, etc

Yeah but it would make it even more resource hungry then. I'm on a 32gb ram machine so I wouldn't feel it but users with lower amounts of ram could be impacted by this elaboration. Just try locally and see how fast it is just to generate the index after the html is done. Of course you can start generating the index from the md files but you would just have to start it as a parallel process as I don't think you can use data you already have during generation unless you do some HEAVY integration between the index generation and the html generation :')

**Comment by KosmosisDire** [comment]
This all makes sense and I am learning a lot about indexing. One last thing is why use the cheerio library instead of just using the html parser, strip out unnecessary parts and grabbing the textContent property. Then we avoid a dependency. Maybe there is something about cheerio though that is a better solution?

**Comment by 7Mik** [comment]
> This all makes sense and I am learning a lot about indexing. One last thing is why use the cheerio library instead of just using the html parser, strip out unnecessary parts and grabbing the textContent property. Then we avoid a dependency. Maybe there is something about cheerio though that is a better solution?

Do you mean htmlparser2? That would be a dependency anyways

**Comment by KosmosisDire** [comment]
No just built in to JavaScript

**Comment by KosmosisDire** [comment]
Like create a DOM out of the html

**Comment by 7Mik** [comment]
> No just built in to JavaScript / Typescript

Oh you mean DOMParser, well I fear that it doesn't have the { xmlMode: true } option that magically saved me while I was trying to handle the ul and li items not being spaced ahahha

**Comment by KosmosisDire** [comment]
But why does the html spacing matter if we are just grabbing text content?

**Comment by 7Mik** [comment]
> But why does the html spacing matter if we are just grabbing text content?

Because somehow an html like `WNT</li><li data-line="1">Slow Growth etc etc` was getting parsed as WNTSlow Growth etc etc and that obviously created a wrong word (WNTSlow) in the index

**Comment by KosmosisDire** [comment]
Ohh, yeah that's not good, I guess the dependency is fine to fix that then.

**Comment by 7Mik** [comment]
> Ohh, yeah that's not good, I guess the dependency is fine to fix that then.

With this last commit I improved performance even more (There was an oversight while parsing ul and li)

Added support for tags. Unfortunately they can't be searched with #*tagname* but will have to be searched by tag~*tagname*.

Simply edit the href of the tags to point to '?q= tag~tagname' to implement tag search functionality

**Comment by KosmosisDire** [comment]
Awesome, I really appreciate the work on this

**Comment by 7Mik** [comment]
The client search script is now ready, too.

All that is left to do now is just add something like <input type="search" placeholder="Search..."> in the html wherever you want it and style it how you want it. 
The results will appear under the searchbar as soon as any word is written (you will also need to style the container)

I commented additional styling so you can decide if you wanna leave it in the js or move it to the css.

Let me know if you need help/troubleshooting with this pr, I will now be moving to the sticker as a logo feature.
If I can tackle the sticker as a logo feature fast enough I will also try to style and put the searchbar to my personal taste :')

**Comment by KosmosisDire** [comment]
Thank you so much, you're amazing :)
I will do a full look over this today or tomorrow

**Comment by 7Mik** [comment]
I saw you added the searchbar setting. That's a nice addition, but then you should also disable the index making. Makes no sense to create an index if it's not gonna be displayed anyways hahah

**Comment by KosmosisDire** [comment]
Ah true. I also need to implement search for offline use. Right now the index is being saved in the vault directory, but if it's being used in a self contained file it needs to be embeded into the file itself. This can be done using the new asset system in version 1.7.4 which isn't in the master branch yet, so I will hold off on that until it's all merged.

Secondly, all of the links actually reload the page instead of loading the document. The events that intercept the normal link behavior need to be set up on the new links. There is a function for this.

Finally, it would probably be good if the links actually directed to the location in the document that that search was found. I don't think this is stored in the index at the moment though.

**Comment by 7Mik** [comment]
> Ah true. I also need to implement search for offline use. Right now the index is being saved in the vault directory, but if it's being used in a self contained file it needs to be embeded into the file itself. This can be done using the new asset system in version 1.7.4 which isn't in the master branch yet, so I will hold off on that until it's all merged.
> 
> Secondly, all of the links actually reload the page instead of loading the document. The events that intercept the normal link behavior need to be set up on the new links. There is a function for this.
> 
> Finally, it would probably be good if the links actually directed to the location in the document that that search was found. I don't think this is stored in the index at the moment though.

I think it's pretty simple to redirect people to the first appearance of the search term and highlight all the appearances of such word. If that's what you mean, I might try to implement it

**Comment by KosmosisDire** [comment]
Ah yes, right. I am going to try and merge everything in 1.7.4 currently into master, and then work can continue with all features together

**Comment by KosmosisDire** [comment]
@7Mik Master has been merged into the 1.7.4 branch, if you'd like to continue work do so by forking the 1.7.4 branch

**Comment by 7Mik** [comment]
> @7Mik Master has been merged into the 1.7.4 branch, if you'd like to continue work do so by forking the 1.7.4 branch

Sure thing! Would it be possible to prepare a project table or a list of things to do? I would love to help!

**Comment by KosmosisDire** [comment]
These are the main bug fixes I am looking at right now:

**Comment by KosmosisDire** [comment]
For some reason after the merge it thinks that I can't construct a Path object which cases the plugin to not load.

**Comment by 7Mik** [comment]
I can look at the index disabling and the tag redirecting since it is pretty much adding to a code I already wrote. Will also look into highlighting and redirecting as you proposed.

For all the other issues, maybe is better if you open a new dedicated issue thread for all of them so we can coordinate better: this thread is becoming quite a mess hahah

**Comment by KosmosisDire** [comment]
Before we can continue we have to fix the Path object problem because it makes it so the plugin doesn't even load to start with. I will create new issues for things as I come to them, and you can do the same.

**Comment by 7Mik** [comment]
> Before we can continue we have to fix the Path object problem because it makes it so the plugin doesn't even load to start with. I will create new issues for things as I come to them, and you can do the same.

Did you already create the issue thread for this path object problem? I will now build from the new 1.7.4 source and see what I can do

**Comment by KosmosisDire** [comment]
@7Mik Just did: #313

**Pull request merged**
