### PR TITLE
Rewrite url() assets in css styles

### PR DESCRIPTION
**Pull request by wyne**
## Overview

Parse through the styles of elements to detect assets in `url()` values. Rewrite those styles for export.

### Before

```html
<div style="color: red; background-image: url('app://......../image.png')"></div>
```

### After

```html
<div style="color: red; background-image: url('attachments/image.png')"></div>
```

## Caveats

- This searches the styles of all elements for usage of `url()`, so it could be very slow on large projects
- For now, the bulk of the existing logic was copied and pasted into the body of this method. Further consolidation can be done to reduce duplicate code.
- Only exported Media is supported so far. Inline media has not been implemented

This works quite well for my project that does custom dataviewjs to create more elaborate UI. I wanted to get a PR up for feedback before I continue further.

### CODE REVIEW

**Comment by KosmosisDire** [comment]
Hi, I beleive I have already implemented this exact feature in 1.7.4 have I not? Or maybe I am misunderstanding what you are doing. could you explain more what you have changed?

**Comment by KosmosisDire** [comment]
Oh wait is this for styles that are actually inline in the markdown document?

**Comment by wyne** [comment]
I'm setting styles manually with the 'dv.el()' method in dataviewjs. Without this, those style attributes weren't getting parsed. 

I can provide a more thorough example when I'm back at a computer.

**Comment by wyne** [comment]
Where in 1.7.4 is the handling that you're referring to? I can double check if it solves the same issue.

**Comment by wyne** [comment]
Oh, I think I see.

https://github.com/KosmosisDire/obsidian-webpage-export/blob/167389ec4823dde609488b90d83cca7d6e26bc52/scripts/html-generation/assets/asset.ts#L95

But I can't tell immediately what gets run through that.

---

Here's my use case. I put this in my markdown file: 

````ts
```dataviewjs
const filePath = (file) => {
    if (file === undefined) { return "none"}
    return file.startsWith("http") ?
        file :
        this.app.vault.adapter.getResourcePath(file)
}
dv.pages('"Posts"').where(p => p.thumbnail !== undefined)
    .sort(item => item.file.name, 'asc')
    .map(item => {
        let bg = `url('${filePath(item.thumbnail.path)}')`;
        let link = "Link text"
        return  dv.el("a", link, {
            cls: ["custom-gallery", "internal-link"],
            attr: {
                href: `${item.file.path}`,
                style: [`background-image: ${bg}`],
                dataBg: `${bg}`
            }
        })
    })
```
````

And it didn't seem to get run through your `createAssetsFromStyles`.

**Comment by KosmosisDire** [comment]
The code I have lready written taken in all the css styles that are included with the document. It does not process the document itself though, so if you end up with inline css styles inside of the document those will not be processes. I think it should be possible to integrate that into the existing assets pipeline pretty simply though without writing too much custom code.

**Comment by wyne** [comment]
Ok, I'll take a look at that and see if I can figure it out.

I'm basically trying to use this plugin to recreate the "read" view of obsidian to turn it into a full-fledged WYSIWYG website editor. And I think that matches with the intentions called out in your readme. Progress so far: https://wyne.github.io/obsidian-vault-website/home.html

**Pull request closed without merging**
