### PR TITLE
fix: tags may be string

### PR DESCRIPTION
**Pull request by royalknight56**
tags can be string

such as:

```
  ---
  tags: blog
  ---
```

#544

### CODE REVIEW

**Comment by KosmosisDire** [comment]
Hey, I have actually fixed this in my local 1.9.0 branch, however I like the other changes you have made so I will go ahead and merge this. Thanks for taking the time to fix this :)

**Comment by KosmosisDire** [comment]
Is it possible for tags to be a number type? Maybe it would be more robust to check if it not an array rather than checking if it is a string?

**Comment by royalknight56** [comment]
You're right. Thanks for pointing that out!

**Comment by KosmosisDire** [comment]
Thanks, this looks pretty good I'll go ahead and pull it in :)

**Pull request merged**
